<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf2e85b2a4ff3ca937e681ca063d2e253
{
    public static $files = array (
        'd90759aa51394cd9815bdd3d1f0723ee' => __DIR__ . '/../..' . '/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Jackal\Extension\\Layout\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jackal\Extension\\Layout\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf2e85b2a4ff3ca937e681ca063d2e253::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf2e85b2a4ff3ca937e681ca063d2e253::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf2e85b2a4ff3ca937e681ca063d2e253::$classMap;
        }, null, ClassLoader::class);
    }
}
